### ISSUE TITLE
Low hashrate after installing of new firmware

### ISSUE THREAD

**Issue by zustri4** [mikelalonde123/YAMI-Tech-YM-100-Miner-Software#5]
Hello, I have the same device and changed the firmware to etc from 2022 (loyal tech), now I have an average hashrate of 1.6 GHS, do you have older firmware for etc?

**Comment by mikelalonde123** [comment]
Try setting the performance mode to “Performance” if it isn’t already. Otherwise I don’t think I have a copy of the old firmware, sorry.
